some checks

diff --git a/.github/workflows/nba_app.yml b/.github/workflows/nba_app.yml
--- a/.github/workflows/nba_app.yml
+++ b/.github/workflows/nba_app.yml
@@ -101,7 +101,17 @@ jobs:
 
       - name: Functional checks for data_ingestion
         run: |
-          docker-compose exec data_ingestion bash -c 'ls -l /app && [ -f /app/signal_data_ingestion_done ] && echo "Data Ingestion Completed" || (echo "Data Ingestion Failed" && exit 1)'
+          retries=0
+          max_retries=5
+          until docker-compose exec data_ingestion bash -c 'ls -l /app && [ -f /app/signal_data_ingestion_done ]'; do
+            retries=$((retries + 1))
+            if [ $retries -gt $max_retries ]; then
+              echo "Data Ingestion failed after $max_retries retries"
+              exit 1
+            fi
+            sleep 10
+          done
+          echo "Data Ingestion Completed"
 
       - name: Functional checks for data_processing
         run: |
